# Generated by Django 3.0.2 on 2020-03-04 08:36

from django.db import migrations
from django.core.management import call_command


def load_sectors(apps, schema_editor):
    call_command("loaddata", "sectors.json")


def load_levels(apps, schema_editor):
    call_command("loaddata", "levels.json")


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_sectors),
        migrations.RunPython(load_levels),
    ]
